// PAGE ACTION TYPES
export const PAGE_CHANGE = 'PAGE_CHANGE';
export const PAGE_SHOW_IN_DEX = 'PAGE_SHOW_IN_DEX';
// POKEMONLIST ACTION TYPES
export const LIST_SET_LENGTH = 'LIST_SET_LENGTH';
export const LIST_SET_SORTING = 'LIST_SET_SORTING';
export const LIST_UPDATE_DATA = 'LIST_UPDATE_DATA';
