// PAGE ACTION TYPES
const PAGE_CHANGE = 'PAGE_CHANGE';
const PAGE_SHOW_IN_DEX = 'PAGE_SHOW_IN_DEX';
const PAGE_UPDATE_DEX_DATA = 'PAGE_UPDATE_DEX_DATA';
// POKEMONLIST ACTION TYPES
const LIST_UPDATE_DATA = 'LIST_UPDATE_DATA';
// COMPARE ACTION TYPES
const COMPARE_ADD_ITEM = 'COMPARE_ADD_ITEM';
const COMPARE_REMOVE_ITEM = 'COMPARE_REMOVE_ITEM';
const COMPARE_UPDATE_DATA = 'COMPARE_UPDATE_DATA';

export {
    PAGE_CHANGE,
    PAGE_SHOW_IN_DEX,
    PAGE_UPDATE_DEX_DATA,
    LIST_UPDATE_DATA,
    COMPARE_ADD_ITEM,
    COMPARE_REMOVE_ITEM,
    COMPARE_UPDATE_DATA,
}
