// PAGE ACTION TYPES
export const PAGE_CHANGE = 'PAGE_CHANGE';
export const PAGE_SHOW_IN_DEX = 'PAGE_SHOW_IN_DEX';
export const PAGE_UPDATE_DEX_DATA = 'PAGE_UPDATE_DEX_DATA';
// POKEMONLIST ACTION TYPES
export const LIST_UPDATE_DATA = 'LIST_UPDATE_DATA';
// COMPARE ACTION TYPES
export const COMPARE_ADD_ITEM = 'COMPARE_ADD_ITEM';
export const COMPARE_REMOVE_ITEM = 'COMPARE_REMOVE_ITEM';
export const COMPARE_UPDATE_DATA = 'COMPARE_UPDATE_DATA';
